// Prints the Homebrew formula for one release, for Go-Vernier/homebrew-tap.
//
//   node scripts/homebrew-formula.mjs <version> <dist-dir>
//
// <dist-dir> holds the release archives' .sha256 files.

import { readFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { normalizeVersion } from "./npm-packages.mjs";
import { TARGETS, assetName } from "./targets.mjs";

const REPO = "https://github.com/Go-Vernier/Vernier-OSS";

export function readSha256(distDir, target) {
  const file = path.join(distDir, `${assetName(target)}.sha256`);
  const hash = readFileSync(file, "utf8").trim().split(/\s+/)[0].toLowerCase();
  if (!/^[0-9a-f]{64}$/.test(hash)) throw new Error(`${file} does not hold a SHA-256`);
  return hash;
}

export function formula(version, sha256Of) {
  const v = normalizeVersion(version);
  const block = (os, cpu) => {
    const t = TARGETS.find((x) => x.os === os && x.cpu === cpu);
    return [
      `      url "${REPO}/releases/download/v${v}/${assetName(t)}"`,
      `      sha256 "${sha256Of(t)}"`,
    ].join("\n");
  };
  return `# Generated by scripts/homebrew-formula.mjs in Go-Vernier/Vernier-OSS. Do not edit by hand.
class Vernier < Formula
  desc "Blast radius of a pull request across services, from code and traces"
  homepage "${REPO}"
  version "${v}"
  license "MIT"

  on_macos do
    on_arm do
${block("darwin", "arm64")}
    end
    on_intel do
${block("darwin", "x64")}
    end
  end

  on_linux do
    on_arm do
${block("linux", "arm64")}
    end
    on_intel do
${block("linux", "x64")}
    end
  end

  def install
    bin.install "vernier"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vernier --version")
  end
end
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const [version, distDir] = process.argv.slice(2);
  if (!distDir) {
    console.error("usage: node scripts/homebrew-formula.mjs <version> <dist-dir>");
    process.exit(2);
  }
  try {
    process.stdout.write(formula(version, (t) => readSha256(distDir, t)));
  } catch (error) {
    console.error(`homebrew-formula: ${error.message}`);
    process.exit(1);
  }
}
