import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { TARGETS } from "../targets.mjs";
import { formula, readSha256 } from "../homebrew-formula.mjs";

const SUMS = {
  "aarch64-apple-darwin": "a".repeat(64),
  "x86_64-apple-darwin": "b".repeat(64),
  "aarch64-unknown-linux-musl": "c".repeat(64),
  "x86_64-unknown-linux-musl": "d".repeat(64),
};
const DL = "https://github.com/Go-Vernier/Vernier-OSS/releases/download/v0.1.0";

test("the formula names each macOS and Linux asset with its checksum", () => {
  assert.equal(
    formula("v0.1.0", (t) => SUMS[t.triple]),
    `# Generated by scripts/homebrew-formula.mjs in Go-Vernier/Vernier-OSS. Do not edit by hand.
class Vernier < Formula
  desc "Blast radius of a pull request across services, from code and traces"
  homepage "https://github.com/Go-Vernier/Vernier-OSS"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "${DL}/vernier-aarch64-apple-darwin.tar.gz"
      sha256 "${"a".repeat(64)}"
    end
    on_intel do
      url "${DL}/vernier-x86_64-apple-darwin.tar.gz"
      sha256 "${"b".repeat(64)}"
    end
  end

  on_linux do
    on_arm do
      url "${DL}/vernier-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${"c".repeat(64)}"
    end
    on_intel do
      url "${DL}/vernier-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${"d".repeat(64)}"
    end
  end

  def install
    bin.install "vernier"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vernier --version")
  end
end
`,
  );
});

test("a checksum is read from sha256sum output and lowercased", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "vernier-dist-"));
  const target = TARGETS.find((t) => t.triple === "aarch64-apple-darwin");
  writeFileSync(path.join(dir, "vernier-aarch64-apple-darwin.tar.gz.sha256"), `${"AB".repeat(32)}  vernier-aarch64-apple-darwin.tar.gz\n`);
  assert.equal(readSha256(dir, target), "ab".repeat(32));
});

test("a file without a checksum is refused", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "vernier-dist-"));
  const target = TARGETS.find((t) => t.triple === "aarch64-apple-darwin");
  writeFileSync(path.join(dir, "vernier-aarch64-apple-darwin.tar.gz.sha256"), "Not Found\n");
  assert.throws(() => readSha256(dir, target), /does not hold a SHA-256/);
});
